"""criando_tabela_blindadas

Revision ID: 16014789aa88
Revises: 
Create Date: 2026-02-18 06:55:24.224583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16014789aa88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_services', 'service_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('appointment_services', 'duration_snapshot',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.drop_column('appointment_services', 'created_at')
    op.add_column('appointment_status_log', sa.Column('from_status', sa.String(), nullable=True))
    op.add_column('appointment_status_log', sa.Column('to_status', sa.String(), nullable=False))
    op.drop_constraint(op.f('appointment_status_log_appointment_id_fkey'), 'appointment_status_log', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_status_log', 'appointments', ['appointment_id'], ['id'])
    op.drop_column('appointment_status_log', 'status')
    op.add_column('appointments', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('appointments', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('appointments', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('unique_idempotency'), 'appointments', type_='unique')
    op.create_index(op.f('ix_appointments_company_id'), 'appointments', ['company_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_unique_constraint('uq_idempotency', 'appointments', ['company_id', 'idempotency_key'])
    op.drop_column('appointments', 'tenant_id')
    op.drop_column('appointments', 'created_at')
    op.create_index(op.f('ix_blocked_slots_company_id'), 'blocked_slots', ['company_id'], unique=False)
    op.create_index(op.f('ix_blocked_slots_professional_id'), 'blocked_slots', ['professional_id'], unique=False)
    op.drop_index(op.f('idx_working_hours_active'), table_name='working_hours', postgresql_where='(is_active = true)')
    op.drop_constraint(op.f('working_hours_company_id_professional_id_weekday_key'), 'working_hours', type_='unique')
    op.create_index(op.f('ix_working_hours_company_id'), 'working_hours', ['company_id'], unique=False)
    op.create_index(op.f('ix_working_hours_professional_id'), 'working_hours', ['professional_id'], unique=False)
    op.create_unique_constraint('uq_working_hours_day', 'working_hours', ['company_id', 'professional_id', 'weekday'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_working_hours_day', 'working_hours', type_='unique')
    op.drop_index(op.f('ix_working_hours_professional_id'), table_name='working_hours')
    op.drop_index(op.f('ix_working_hours_company_id'), table_name='working_hours')
    op.create_unique_constraint(op.f('working_hours_company_id_professional_id_weekday_key'), 'working_hours', ['company_id', 'professional_id', 'weekday'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_working_hours_active'), 'working_hours', ['company_id', 'professional_id'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_blocked_slots_professional_id'), table_name='blocked_slots')
    op.drop_index(op.f('ix_blocked_slots_company_id'), table_name='blocked_slots')
    op.add_column('appointments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_idempotency', 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_company_id'), table_name='appointments')
    op.create_unique_constraint(op.f('unique_idempotency'), 'appointments', ['tenant_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('appointments', 'idempotency_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'version')
    op.drop_column('appointments', 'company_id')
    op.add_column('appointment_status_log', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointment_status_log', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_status_log_appointment_id_fkey'), 'appointment_status_log', 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointment_status_log', 'to_status')
    op.drop_column('appointment_status_log', 'from_status')
    op.add_column('appointment_services', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('appointment_services', 'duration_snapshot',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('appointment_services', 'service_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
