"""criando_tabelas_blindadas

Revision ID: 36e2e1f526da
Revises: 16014789aa88
Create Date: 2026-02-21 07:27:01.811725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e2e1f526da'
down_revision: Union[str, Sequence[str], None] = '16014789aa88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # [retrofit baseline e0s00] working_hours já nasce na baseline com o
    # shape REAL de produção (default gen_random_uuid + FKs, sem índices
    # ix_*) — este create_table foi gerado contra um banco que divergia.
    # Guard de existência: no replay em banco vazio, vira no-op.
    from sqlalchemy import text
    conn = op.get_bind()
    exists = conn.execute(text(
        "SELECT 1 FROM information_schema.tables "
        "WHERE table_schema = 'public' AND table_name = 'working_hours'"
    )).fetchone()
    if exists:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'professional_id', 'weekday', name='uq_working_hours_day')
    )
    op.create_index(op.f('ix_working_hours_company_id'), 'working_hours', ['company_id'], unique=False)
    op.create_index(op.f('ix_working_hours_professional_id'), 'working_hours', ['professional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_hours_professional_id'), table_name='working_hours')
    op.drop_index(op.f('ix_working_hours_company_id'), table_name='working_hours')
    op.drop_table('working_hours')
    # ### end Alembic commands ###
