"""add cancelled fields to appointment

Revision ID: 540331d2c848
Revises: 36e2e1f526da
Create Date: 2026-04-09 07:13:53.835760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '540331d2c848'
down_revision: Union[str, Sequence[str], None] = '36e2e1f526da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_services', 'service_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('appointment_services', 'duration_snapshot',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.drop_constraint(op.f('appointment_services_appointment_id_fkey'), 'appointment_services', type_='foreignkey')
    op.drop_constraint(op.f('fk_appointment_services_company'), 'appointment_services', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_services', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'appointment_services', 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointment_services', 'company_id')
    op.drop_constraint(op.f('fk_status_log_company'), 'appointment_status_log', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_status_log', 'appointments', ['appointment_id'], ['id'])
    op.drop_column('appointment_status_log', 'changed_by')
    op.drop_column('appointment_status_log', 'company_id')
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.alter_column('appointments', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'total_commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('appointments', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('appointments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_appointments_conflict'), table_name='appointments', postgresql_where="(status = ANY (ARRAY['pending'::text, 'confirmed'::text]))")
    op.drop_constraint(op.f('unique_idempotency_per_company'), 'appointments', type_='unique')
    op.create_unique_constraint('uq_idempotency', 'appointments', ['company_id', 'idempotency_key'])
    op.create_foreign_key(None, 'appointments', 'users', ['cancelled_by'], ['id'])
    op.drop_column('appointments', 'financial_status')
    op.alter_column('clients', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('clients', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('professional_services_professional_id_service_id_key'), 'professional_services', type_='unique')
    op.alter_column('professionals', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.create_unique_constraint('uq_working_hours_day', 'working_hours', ['company_id', 'professional_id', 'weekday'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_working_hours_day', 'working_hours', type_='unique')
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('professionals', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('professional_services_professional_id_service_id_key'), 'professional_services', ['professional_id', 'service_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clients', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('clients', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('appointments', sa.Column('financial_status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint('uq_idempotency', 'appointments', type_='unique')
    op.create_unique_constraint(op.f('unique_idempotency_per_company'), 'appointments', ['company_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_appointments_conflict'), 'appointments', ['professional_id', 'start_at', 'end_at'], unique=False, postgresql_where="(status = ANY (ARRAY['pending'::text, 'confirmed'::text]))")
    op.alter_column('appointments', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('appointments', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('appointments', 'idempotency_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('appointments', 'total_commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'end_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('appointments', 'start_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('appointments', 'cancelled_by')
    op.drop_column('appointments', 'cancelled_at')
    op.add_column('appointment_status_log', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('appointment_status_log', sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment_status_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_status_log_company'), 'appointment_status_log', 'companies', ['company_id'], ['id'])
    op.add_column('appointment_services', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointment_services', type_='foreignkey')
    op.drop_constraint(None, 'appointment_services', type_='foreignkey')
    op.create_foreign_key(op.f('fk_appointment_services_company'), 'appointment_services', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('appointment_services_appointment_id_fkey'), 'appointment_services', 'appointments', ['appointment_id'], ['id'])
    op.alter_column('appointment_services', 'duration_snapshot',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('appointment_services', 'service_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
