"""add financial_status

Revision ID: a8c81686f38e
Revises: 540331d2c848
Create Date: 2026-04-10 06:29:50.350159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c81686f38e'
down_revision: Union[str, Sequence[str], None] = '540331d2c848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # [retrofit baseline e0s00] produção tem financial_status como VARCHAR e
    # o tipo financial_status_enum NÃO existe lá (foi convertido/removido à
    # mão). O Enum original também quebraria f3a9e1d72b04, que faz UPDATE
    # para 'UNPAID'/'PAID'/'REFUNDED' (valores fora do enum) e SET DEFAULT
    # 'UNPAID'. VARCHAR reproduz produção e mantém a cadeia executável.
    op.add_column('appointments', sa.Column('financial_status', sa.String(), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'financial_status')
    # ### end Alembic commands ###
