"""add financial_status

Revision ID: a8c81686f38e
Revises: 540331d2c848
Create Date: 2026-04-10 06:29:50.350159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c81686f38e'
down_revision: Union[str, Sequence[str], None] = '540331d2c848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('financial_status', sa.Enum('pending', 'paid', 'cancelled', 'refunded', name='financial_status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'financial_status')
    # ### end Alembic commands ###
